### ISSUE TITLE
Error al realizar Geotiff de viento

### ISSUE THREAD

**Issue by RomiNahir** [INTA-Radar/radar-cmd#4]
Aparece un error cuando se quiere realizar el geotiff de la variable viento.

python radar-cmd.py -d /media/romina/datos/Radar_Meteo/informes/Info_viento_3mar19/datos/viento/ -ele 0 -var auto -gtif 

Traceback (most recent call last):
  File "radar-cmd.py", line 296, in <module>
    rrp.saveToGTiff(level, dirname(file_out)+'/', basename(file_out))
  File "/media/romina/datos/radarcmd/radar-cmd/Procesador/RainbowRadarProcessor.py", line 383, in saveToGTiff
    warp=True
  File "/media/romina/datos/radarcmd/lib/python3.6/site-packages/pyart/io/output_to_geotiff.py", line 144, in write_grid_geotiff
    data, vmin, vmax, color_levels, cmap)
  File "/media/romina/datos/radarcmd/lib/python3.6/site-packages/pyart/io/output_to_geotiff.py", line 204, in _get_rgb_values
    frac = (data - vmin) / np.float(vmax-vmin)
TypeError: unsupported operand type(s) for -: 'float' and 'NoneType'

**Comment by giordand** [comment]
En ves de -ele proba con -level, ya que la herramienta siempre genera un CAPPI por defecto. Para visualizar las elevaciones de forma individual tenes que indicar `-img_method simple` y ahí si le pedís una elevación especifica con el parámetro `-ele`. Quizas el problema venga por este lado, probalo y vemos.

**Comment by RomiNahir** [comment]
Hice estas pruebas y sigue dando el mismo error.. esta bien lo que estoy poniendo?

python radar-cmd.py -d /media/romina/datos/Radar_Meteo/informes/Info_viento_3mar19/datos/viento/ -level 0 -var auto -gtif

python radar-cmd.py -d /media/romina/datos/Radar_Meteo/informes/Info_viento_3mar19/datos/viento/ -ele 0 -var auto -img_method simple -gtif
